export default {
  C: [{ notes: ["C4", "E4", "G4"], duration: 1 }],
  Dm: [{ notes: ["D4", "F4", "A4"], duration: 1 }],
  Em: [{ notes: ["E4", "G4", "B4"], duration: 1 }],
  F: [{ notes: ["F4", "A4", "C4"], duration: 1 }],
  G: [{ notes: ["G4", "B4", "D4"], duration: 1 }],
  Am: [{ notes: ["A4", "C4", "E4"], duration: 1 }],
  D: [{ notes: ["D4", "F#4", "A4"], duration: 1 }],
  "F#m": [{ notes: ["F#4", "A4", "C#4"], duration: 1 }],
  A: [{ notes: ["A4", "C#4", "E4"], duration: 1 }],
  Bm: [{ notes: ["B4", "D4", "F#4"], duration: 1 }],
  E: [{ notes: ["E4", "G#4", "B4"], duration: 1 }],
  "F#": [{ notes: ["F#4", "A#4", "C#4"], duration: 1 }],
  "G#m": [{ notes: ["G#4", "B4", "D#4"], duration: 1 }],
  B: [{ notes: ["A#4", "D#4", "F#4"], duration: 1 }],
  "C#m": [{ notes: ["C#4", "E4", "G#4"], duration: 1 }],
  Gm: [{ notes: ["G4", "Bb4", "D4"], duration: 1 }],
  Bb: [{ notes: ["A#4", "D4", "F4"], duration: 1 }],
  "D#m": [{ notes: ["D#4", "F#4", "A#4"], duration: 1 }]
};
