export default {
  C: [
    { notes: ["C4", "E4", "G4"], duration: 1 },
    { notes: ["E4"], duration: 1 },
    { notes: ["G4"], duration: 1 },
    { notes: ["C5"], duration: 1 },
    { notes: ["C4"], duration: 1 },
    { notes: ["E4"], duration: 1 },
    { notes: ["G4"], duration: 1 },
    { notes: ["C5"], duration: 1 },
    { notes: ["C4"], duration: 1 },
    { notes: ["E4"], duration: 1 },
    { notes: ["G4"], duration: 1 },
    { notes: ["C5"], duration: 1 },
    { notes: ["C4"], duration: 1 },
    { notes: ["E4"], duration: 1 },
    { notes: ["G4"], duration: 1 },
    { notes: ["C5"], duration: 1 }
  ],
  Dm: [
    { notes: ["D4", "F4", "A4"], duration: 1 },
    { notes: ["F4"], duration: 1 },
    { notes: ["A4"], duration: 1 },
    { notes: ["D5"], duration: 1 },
    { notes: ["D4"], duration: 1 },
    { notes: ["F4"], duration: 1 },
    { notes: ["A4"], duration: 1 },
    { notes: ["D5"], duration: 1 },
    { notes: ["D4"], duration: 1 },
    { notes: ["F4"], duration: 1 },
    { notes: ["A4"], duration: 1 },
    { notes: ["D5"], duration: 1 },
    { notes: ["D4"], duration: 1 },
    { notes: ["F4"], duration: 1 },
    { notes: ["A4"], duration: 1 },
    { notes: ["D5"], duration: 1 }
  ],
  Em: [
    { notes: ["E4", "G4", "B4"], duration: 1 },
    { notes: ["G4"], duration: 1 },
    { notes: ["B4"], duration: 1 },
    { notes: ["E5"], duration: 1 },
    { notes: ["E4"], duration: 1 },
    { notes: ["G4"], duration: 1 },
    { notes: ["B4"], duration: 1 },
    { notes: ["E5"], duration: 1 },
    { notes: ["E4"], duration: 1 },
    { notes: ["G4"], duration: 1 },
    { notes: ["B4"], duration: 1 },
    { notes: ["E5"], duration: 1 },
    { notes: ["E4"], duration: 1 },
    { notes: ["G4"], duration: 1 },
    { notes: ["B4"], duration: 1 },
    { notes: ["E5"], duration: 1 }
  ],
  F: [
    { notes: ["F4", "A4", "C4"], duration: 1 },
    { notes: ["A4"], duration: 1 },
    { notes: ["C4"], duration: 1 },
    { notes: ["F5"], duration: 1 },
    { notes: ["F4"], duration: 1 },
    { notes: ["A4"], duration: 1 },
    { notes: ["C4"], duration: 1 },
    { notes: ["F5"], duration: 1 },
    { notes: ["F4"], duration: 1 },
    { notes: ["A4"], duration: 1 },
    { notes: ["C4"], duration: 1 },
    { notes: ["F5"], duration: 1 },
    { notes: ["F4"], duration: 1 },
    { notes: ["A4"], duration: 1 },
    { notes: ["C4"], duration: 1 },
    { notes: ["F5"], duration: 1 }
  ],
  G: [
    { notes: ["G4", "B4", "D4"], duration: 1 },
    { notes: ["B4"], duration: 1 },
    { notes: ["D4"], duration: 1 },
    { notes: ["G5"], duration: 1 },
    { notes: ["G4"], duration: 1 },
    { notes: ["B4"], duration: 1 },
    { notes: ["D4"], duration: 1 },
    { notes: ["G5"], duration: 1 },
    { notes: ["G4"], duration: 1 },
    { notes: ["B4"], duration: 1 },
    { notes: ["D4"], duration: 1 },
    { notes: ["G5"], duration: 1 },
    { notes: ["G4"], duration: 1 },
    { notes: ["B4"], duration: 1 },
    { notes: ["D4"], duration: 1 },
    { notes: ["G5"], duration: 1 }
  ],
  Am: [
    { notes: ["A4", "C4", "E4"], duration: 1 },
    { notes: ["C4"], duration: 1 },
    { notes: ["E4"], duration: 1 },
    { notes: ["A5"], duration: 1 },
    { notes: ["A4"], duration: 1 },
    { notes: ["C4"], duration: 1 },
    { notes: ["E4"], duration: 1 },
    { notes: ["A5"], duration: 1 },
    { notes: ["A4"], duration: 1 },
    { notes: ["C4"], duration: 1 },
    { notes: ["E4"], duration: 1 },
    { notes: ["A5"], duration: 1 },
    { notes: ["A4"], duration: 1 },
    { notes: ["C4"], duration: 1 },
    { notes: ["E4"], duration: 1 },
    { notes: ["A5"], duration: 1 }
  ],
  D: [
    { notes: ["D4", "F#4", "A4"], duration: 1 },
    { notes: ["F#4"], duration: 1 },
    { notes: ["A4"], duration: 1 },
    { notes: ["D5"], duration: 1 },
    { notes: ["D4"], duration: 1 },
    { notes: ["F#4"], duration: 1 },
    { notes: ["A4"], duration: 1 },
    { notes: ["D5"], duration: 1 },
    { notes: ["D4"], duration: 1 },
    { notes: ["F#4"], duration: 1 },
    { notes: ["A4"], duration: 1 },
    { notes: ["D5"], duration: 1 },
    { notes: ["D4"], duration: 1 },
    { notes: ["F#4"], duration: 1 },
    { notes: ["A4"], duration: 1 },
    { notes: ["D5"], duration: 1 }
  ],
  "F#m": [
    { notes: ["Gb4", "A4", "Db4"], duration: 1 },
    { notes: ["A4"], duration: 1 },
    { notes: ["Db4"], duration: 1 },
    { notes: ["Gb5"], duration: 1 },
    { notes: ["Gb4"], duration: 1 },
    { notes: ["A4"], duration: 1 },
    { notes: ["Db4"], duration: 1 },
    { notes: ["Gb5"], duration: 1 },
    { notes: ["Gb4"], duration: 1 },
    { notes: ["A4"], duration: 1 },
    { notes: ["Db4"], duration: 1 },
    { notes: ["Gb5"], duration: 1 },
    { notes: ["Gb4"], duration: 1 },
    { notes: ["A4"], duration: 1 },
    { notes: ["Db4"], duration: 1 },
    { notes: ["Gb5"], duration: 1 }
  ],
  A: [
    { notes: ["A4", "C#4", "E4"], duration: 1 },
    { notes: ["C#4"], duration: 1 },
    { notes: ["E4"], duration: 1 },
    { notes: ["C#5"], duration: 1 },
    { notes: ["C#4"], duration: 1 },
    { notes: ["C#4"], duration: 1 },
    { notes: ["E4"], duration: 1 },
    { notes: ["C#5"], duration: 1 },
    { notes: ["C#4"], duration: 1 },
    { notes: ["C#4"], duration: 1 },
    { notes: ["E4"], duration: 1 },
    { notes: ["C#5"], duration: 1 },
    { notes: ["C#4"], duration: 1 },
    { notes: ["C#4"], duration: 1 },
    { notes: ["E4"], duration: 1 },
    { notes: ["C#5"], duration: 1 }
  ],
  Bm: [
    { notes: ["B4", "D4", "Gb4"], duration: 1 },
    { notes: ["D4"], duration: 1 },
    { notes: ["Gb4"], duration: 1 },
    { notes: ["B5"], duration: 1 },
    { notes: ["B4"], duration: 1 },
    { notes: ["D4"], duration: 1 },
    { notes: ["Gb4"], duration: 1 },
    { notes: ["B5"], duration: 1 },
    { notes: ["B4"], duration: 1 },
    { notes: ["D4"], duration: 1 },
    { notes: ["Gb4"], duration: 1 },
    { notes: ["B5"], duration: 1 },
    { notes: ["B4"], duration: 1 },
    { notes: ["D4"], duration: 1 },
    { notes: ["Gb4"], duration: 1 },
    { notes: ["B5"], duration: 1 }
  ],
  E: [
    { notes: ["E4", "G#4", "B4"], duration: 1 },
    { notes: ["G#4"], duration: 1 },
    { notes: ["B4"], duration: 1 },
    { notes: ["E5"], duration: 1 },
    { notes: ["E4"], duration: 1 },
    { notes: ["G#4"], duration: 1 },
    { notes: ["B4"], duration: 1 },
    { notes: ["E5"], duration: 1 },
    { notes: ["E4"], duration: 1 },
    { notes: ["G#4"], duration: 1 },
    { notes: ["B4"], duration: 1 },
    { notes: ["E5"], duration: 1 },
    { notes: ["E4"], duration: 1 },
    { notes: ["G#4"], duration: 1 },
    { notes: ["B4"], duration: 1 },
    { notes: ["E5"], duration: 1 }
  ],
  "F#": [
    { notes: ["Gb4", "Bb4", "Db4"], duration: 1 },
    { notes: ["Bb4"], duration: 1 },
    { notes: ["Db4"], duration: 1 },
    { notes: ["Gb5"], duration: 1 },
    { notes: ["Gb4"], duration: 1 },
    { notes: ["Bb4"], duration: 1 },
    { notes: ["Db4"], duration: 1 },
    { notes: ["Gb5"], duration: 1 },
    { notes: ["Gb4"], duration: 1 },
    { notes: ["Bb4"], duration: 1 },
    { notes: ["Db4"], duration: 1 },
    { notes: ["Gb5"], duration: 1 },
    { notes: ["Gb4"], duration: 1 },
    { notes: ["Bb4"], duration: 1 },
    { notes: ["Db4"], duration: 1 },
    { notes: ["Gb5"], duration: 1 }
  ],
  "G#m": [
    { notes: ["Ab4", "B4", "Eb4"], duration: 1 },
    { notes: ["B4"], duration: 1 },
    { notes: ["Eb4"], duration: 1 },
    { notes: ["Ab5"], duration: 1 },
    { notes: ["Ab4"], duration: 1 },
    { notes: ["B4"], duration: 1 },
    { notes: ["Eb4"], duration: 1 },
    { notes: ["Ab5"], duration: 1 },
    { notes: ["Ab4"], duration: 1 },
    { notes: ["B4"], duration: 1 },
    { notes: ["Eb4"], duration: 1 },
    { notes: ["Ab5"], duration: 1 },
    { notes: ["Ab4"], duration: 1 },
    { notes: ["B4"], duration: 1 },
    { notes: ["Eb4"], duration: 1 },
    { notes: ["Ab5"], duration: 1 }
  ],
  B: [
    { notes: ["Bb4", "Eb4", "Gb4"], duration: 1 },
    { notes: ["Eb4"], duration: 1 },
    { notes: ["Gb4"], duration: 1 },
    { notes: ["Bb5"], duration: 1 },
    { notes: ["Bb4"], duration: 1 },
    { notes: ["Eb4"], duration: 1 },
    { notes: ["Gb4"], duration: 1 },
    { notes: ["Bb5"], duration: 1 },
    { notes: ["Bb4"], duration: 1 },
    { notes: ["Eb4"], duration: 1 },
    { notes: ["Gb4"], duration: 1 },
    { notes: ["Bb5"], duration: 1 },
    { notes: ["Bb4"], duration: 1 },
    { notes: ["Eb4"], duration: 1 },
    { notes: ["Gb4"], duration: 1 },
    { notes: ["Bb5"], duration: 1 }
  ],
  "C#m": [
    { notes: ["Db4", "E4", "Ab4"], duration: 1 },
    { notes: ["E4"], duration: 1 },
    { notes: ["Ab4"], duration: 1 },
    { notes: ["Db5"], duration: 1 },
    { notes: ["Db4"], duration: 1 },
    { notes: ["E4"], duration: 1 },
    { notes: ["Ab4"], duration: 1 },
    { notes: ["Db5"], duration: 1 },
    { notes: ["Db4"], duration: 1 },
    { notes: ["E4"], duration: 1 },
    { notes: ["Ab4"], duration: 1 },
    { notes: ["Db5"], duration: 1 },
    { notes: ["Db4"], duration: 1 },
    { notes: ["E4"], duration: 1 },
    { notes: ["Ab4"], duration: 1 },
    { notes: ["Db5"], duration: 1 }
  ],
  Gm: [
    { notes: ["G4", "Bb4", "D4"], duration: 1 },
    { notes: ["Bb4"], duration: 1 },
    { notes: ["D4"], duration: 1 },
    { notes: ["G5"], duration: 1 },
    { notes: ["G4"], duration: 1 },
    { notes: ["Bb4"], duration: 1 },
    { notes: ["D4"], duration: 1 },
    { notes: ["G5"], duration: 1 },
    { notes: ["G4"], duration: 1 },
    { notes: ["Bb4"], duration: 1 },
    { notes: ["D4"], duration: 1 },
    { notes: ["G5"], duration: 1 },
    { notes: ["G4"], duration: 1 },
    { notes: ["Bb4"], duration: 1 },
    { notes: ["D4"], duration: 1 },
    { notes: ["G5"], duration: 1 }
  ],
  Bb: [
    { notes: ["Bb4", "D4", "F4"], duration: 1 },
    { notes: ["D4"], duration: 1 },
    { notes: ["F4"], duration: 1 },
    { notes: ["Bb5"], duration: 1 },
    { notes: ["Bb4"], duration: 1 },
    { notes: ["D4"], duration: 1 },
    { notes: ["F4"], duration: 1 },
    { notes: ["Bb5"], duration: 1 },
    { notes: ["Bb4"], duration: 1 },
    { notes: ["D4"], duration: 1 },
    { notes: ["F4"], duration: 1 },
    { notes: ["Bb5"], duration: 1 },
    { notes: ["Bb4"], duration: 1 },
    { notes: ["D4"], duration: 1 },
    { notes: ["F4"], duration: 1 },
    { notes: ["Bb5"], duration: 1 }
  ],
  "D#m": [
    { notes: ["Eb4", "Gb4", "Bb4"], duration: 1 },
    { notes: ["Gb4"], duration: 1 },
    { notes: ["Bb4"], duration: 1 },
    { notes: ["Eb5"], duration: 1 },
    { notes: ["Eb4"], duration: 1 },
    { notes: ["Gb4"], duration: 1 },
    { notes: ["Bb4"], duration: 1 },
    { notes: ["Eb5"], duration: 1 },
    { notes: ["Eb4"], duration: 1 },
    { notes: ["Gb4"], duration: 1 },
    { notes: ["Bb4"], duration: 1 },
    { notes: ["Eb5"], duration: 1 },
    { notes: ["Eb4"], duration: 1 },
    { notes: ["Gb4"], duration: 1 },
    { notes: ["Bb4"], duration: 1 },
    { notes: ["Eb5"], duration: 1 }
  ]
};
